apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: d
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-abcf2b47-ff4e-42ee-9600-ff36e3a3f006
      eventName: github-abcf2b47-ff4e-42ee-9600-ff36e3a3f006
      eventSourceName: d
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - delete
            type: string
          - path: body.refType
            value:
              - branch
            type: string
  triggers:
    - template:
        name: d
        conditions: github-abcf2b47-ff4e-42ee-9600-ff36e3a3f006
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: d-d-
              spec:
                workflowTemplateRef:
                  name: argo-hub.ci-simple.0.0.1
          parameters: []
